---
- include_vars: node12.yml
  when: nodejs_version.startswith("0.12.")
- include_vars: node10.yml
  when: nodejs_version.startswith("0.10.")
- include_vars: node4x.yml
  when: nodejs_version.startswith("4.")
- include_vars: node5x.yml
  when: nodejs_version.startswith("5.")
- include_vars: node6x.yml
  when: nodejs_version.startswith("6.")
- include_vars: node7x.yml
  when: nodejs_version.startswith("7.")
- include_vars: node8x.yml
  when: nodejs_version.startswith("8.")
- fail: 'msg="supported nodejs_version are 0.10, 0.12, 4, 5, 6, 7 or 8"'
  when: nodejs_source_pub is not defined
